title: "Mobius Code"
markdown: GFM
highlighter: rouge

#remote_theme: just-the-docs/just-the-docs
#remote_theme: abhinavs/moonwalk
#remote_theme: cotes2020/jekyll-theme-chirpy
#remote_theme: b2a3e8/jekyll-theme-console
